### PR TITLE
NMatrix version

### PR DESCRIPTION
**Pull request by Enucatl**
Hey, I found out that the NMatrix library is under active development, so I updated your code to use it. As a positive side effect, hdf5 can be a pure ruby gem since the data pointer is provided already by nmatrix itself.

### CODE REVIEW

**Comment by edmundhighcock** [comment]
Hi Matteo and Enucatl,

Sorry for taking a while to get back to you. These changes look great. I will test them today and hopefully have them pushed up to rubygems very soon.

Thanks for helping out!

Edmund

**Comment by Enucatl** [comment]
Hi Edmund,

Matteo and Enucatl are the same guy (me :)

There is a catch though: NMatrix doesn't (and won't apparently) support unsigned int types. This means that my fork can only read signed int, float and complex datasets. Check [the discussion here](https://github.com/SciRuby/nmatrix/issues/282) and let me know if you have any idea on how to improve this.

**Comment by edmundhighcock** [comment]
Hi Matteo

Well, I didn't want to offend anyone by leaving them off. :-)

The lack of unsigned integers doesn't bother me as I am only using the data from scientific codes, which is generally floating point. Furthermore, NArrays don't have to be the only output option for the hdf5 module… People could use it to read data into any object which had a chunk of memory of the right size and a ruby function to return the memory location. I just happened to implement NArray first because it was very easy and I use NArrays throughout my main project [edmundhighcock/coderunner](https://github.com/edmundhighcock/coderunner).

On that note, do you know if the object created by `NMatrix.new(dtspce.dims.reverse, dtype: narray_type)`  behaves in exactly the same way as the original NArray? My projects are riddled with references to NArrays, and it would be a problem for me if there were some differences between them.

Going back to the discussion you referenced, in the case of your unsigned integer types, where do you want the data to end up? Couldn't you write a new little function in the hdf5 gem which which reads data directly into the objects you use for your image processing, rather than going through NMatrix?

**Comment by Enucatl** [comment]
Well, the objects I wanted to use for the image processing would be the NMatrix (-ces), since they come with all the needed mathematical functions. A `pickable` string would also probably work.

On the other hand, I had to change quite a few things (not a lot, but if you have many occurrences...) when changing from NArray to NMatrix. It really is a rewrite, and it doesn't look like keeping the same interface was a priority. I'm not an expert on either library though, you might want to test yourself.

**Comment by edmundhighcock** [comment]
Perhaps the end of your post was cut off?

Well, I will test the changes with the rest of my code. It may be that for the moment I try to support both options. However, it would be good to move to something like NMatrix, which is in active development, and try to integrate my code in general with the SciRuby effort, so in the medium term I will move in that direction.

Hopefully I'll get back to you in the next few days on my testing.

**Comment by Enucatl** [comment]
no that's ok, I just wanted to cut the last sentence :)

Then you can write me here when you come to a conclusion regarding NMatrix. I'm quite fond of unsigned int types, I still hope I can find a good solution for them.

**Pull request closed without merging**
